version: "1.0"

volumes:
  link_shortener_pg:

services:
  link_shortener_db:
    image: postgres:16.0-alpine
    container_name: link_shortener_db
    restart: always
    ports:
      - "5431:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=link_shortener_db
    volumes:
      - link_shortener_pg:/var/lib/postgresql/data
    networks:
      - net

  application:
    container_name: LinkShortenerApp
    build: .
    ports:
      - "8082:8080"
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://link_shortener_db:5432/link_shortener_db'
      SPRING_DATASOURCE_USERNAME: 'admin'
      SPRING_DATASOURCE_PASSWORD: '12345'
    depends_on:
      - link_shortener_db
    networks:
      - net

networks:
  net:
    driver: bridge